development:
  clients:
    default:
      database: mastermind_development
      hosts:
        - db:27017
      options:
  options:
production:
  clients:
    default:
      database: mastermind_production
      hosts:
        - db:27017
      options:
test:
  clients:
    default:
      database: mastermind_test
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
