# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d873a75e86e73cb5f0f18961b08d2ea721fe676b050e35caeee3c1e8afb96f62a76f7c8f041417f4f26dc1895831c8dc492589a5f599d14155ae8cf8a33b2e2b
  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: axiom_mastermind_bot

test:
  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: axiom_mastermind_bot
  secret_key_base: cd7f42ca1d03372280e76cd0e073970bd3522f5986f6a2eccba26782ac66ffcd30655abea290aba9291ec8b75b690b1d3ccfe1451942367453e9d4e867e58466

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: axiom_mastermind_bot
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
